global_costmap:
  global_frame: tb3_1/map
  robot_base_frame: tb3_1/base_footprint

  update_frequency: 5.0 #was 10.0
  publish_frequency: 5.0 #was 10.0
  transform_tolerance: 0.5

  # static_map: false
  # rolling_window: true
  static_map: true

# inflater_layer:
#   inflation_radius: 0.55 #default of 0.55
  # cost_scaling_factor: 2.5
 
